#!/bin/bash

dotfiles=()

readarray -d '' dotfiles < <(find . -type f ! -path '*/.git/*' ! -name "README.md" -type f -print0)

for file in ${dotfiles[@]}; do
                dir=$(dirname $file | sed s#.#$HOME#1)
                [ ! -d $dir ] && echo "directory $dir not exist!" && mkdir -p $dir

                # Create path strings
		real=$PWD/${file#./}
    		symlink=$HOME/${file#./}
		ln -sv $real $symlink

done

exit
